builders:
  stormberry:
    import: "package:stormberry/builder.dart"
    builder_factories: [ "analyzeSchema" ]
    build_extensions: { ".dart": ["___"] }
    auto_apply: dependents
    build_to: cache
    runs_before: ["stormberry|schema", "stormberry|runner"]
  schema:
    import: "package:stormberry/builder.dart"
    builder_factories: [ "buildSchema" ]
    build_extensions: { ".dart": [ ".schema.dart" ] }
    auto_apply: dependents
    build_to: source
  runner:
    import: "package:stormberry/builder.dart"
    builder_factories: [ "buildRunner" ]
    build_extensions: { ".dart": [ ".runner.dart" ] }
    auto_apply: dependents
    build_to: cache