name: Dart CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Analyze and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3

      - name: Bootstrap
        run: |
          dart pub get
          dart pub global activate coverage
          
      - name: Check formatting
        run: dart format . --set-exit-if-changed --line-length=100

      - name: Run Code Gen
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Lint
        run: dart analyze . --fatal-infos

      - name: Pull Postgres Image
        run: docker pull postgres:latest

      - name: Run Tests
        run: dart test --concurrency=1 --coverage=coverage

      - name: Format Coverage
        run: dart pub global run coverage:format_coverage --check-ignore --packages=.dart_tool/package_config.json --report-on=lib --lcov -o "./coverage/lcov.info" -i ./coverage
           # genhtml coverage/lcov.info -o coverage/report

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info
